services:
  - type: web
    name: satellite-collision-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
